"""init

Revision ID: 476284900a69
Revises: 
Create Date: 2025-08-21 17:02:59.177700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '476284900a69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_fuel_price_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=False),
    sa.Column('litres', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.CheckConstraint('litres >= 0', name='ck_inventory_nonnegative'),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_type_id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fuel_type_id', sa.Integer(), nullable=True),
    sa.Column('litres', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('price_at_sale', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_sale_amount_nonnegative'),
    sa.CheckConstraint('litres > 0', name='ck_sale_litres_positive'),
    sa.CheckConstraint('price_at_sale >= 0', name='ck_sale_price_nonnegative'),
    sa.ForeignKeyConstraint(['fuel_type_id'], ['fuel_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_pkey'))
    )
    op.drop_table('sales')
    op.drop_table('inventory')
    op.drop_table('fuel_types')
    # ### end Alembic commands ###
